<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Blog;
use Illuminate\Support\Str;
use Carbon\Carbon;

class BlogSeeder extends Seeder
{
    public function run(): void
    {
        Blog::truncate();

        $blogs = [
            [
                'title' => "Architecting Multi-Tenant SaaS Platforms in Laravel & MySQL",
                'category' => "SaaS Architecture",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Deep dive into tenant database isolation models, dynamic domain routing middleware, and row-level security for high-enterprise SaaS platforms.",
                'content' => "Multi-tenancy is the foundational architecture pattern of modern SaaS platforms where a single deployed application serves multiple distinct organizational customers (tenants). Each tenant requires absolute data isolation, customized branding, and secure user management without risking cross-tenant data leakage.\n\n### 1. Database Isolation Models in Multi-Tenant Applications\n\nWhen engineering a SaaS application, selecting the appropriate database isolation strategy determines long-term scalability, maintenance effort, and compliance security:\n\n- **Single Database with Row-Level Isolation (Tenant ID):** Every database table contains a tenant_id foreign key. While cost-effective and simple to back up, it relies heavily on application-level global scopes to prevent data leaks.\n- **Database Per Tenant (Isolated Databases):** Each tenant receives a dedicated MySQL/PostgreSQL database. This strategy offers maximum security, compliance (GDPR/HIPAA), and customizable tenant migrations.\n- **Schema Per Tenant (PostgreSQL):** Uses separate database schemas within a single Postgres instance, providing clean logical separation with lower overhead than dedicated database servers.\n\n### 2. Implementing Dynamic Subdomain Resolution Middleware\n\nIn Laravel, dynamic tenant resolution is typically handled in an HTTP middleware layer executed before controller action dispatching:\n\n```php\nnamespace App\\Http\\Middleware;\n\nuse Closure;\nuse App\\Models\\Tenant;\n\nclass ResolveTenant\n{\n    public function handle(\$request, Closure \$next)\n    {\n        \$host = \$request->getHost();\n        \$subdomain = explode('.', \$host)[0];\n\n        \$tenant = Tenant::where('subdomain', \$subdomain)->first();\n        if (!\$tenant) {\n            abort(404, 'Tenant domain not configured.');\n        }\n\n        // Bind active tenant into Laravel Service Container & switch DB connection\n        app()->instance('tenant', \$tenant);\n        config(['database.connections.tenant.database' => \$tenant->db_name]);\n        \\DB::purge('tenant');\n        \\DB::reconnect('tenant');\n\n        return \$next(\$request);\n    }\n}\n```\n\n### 3. Automated Statutory Compliance & Tenant Isolation\n\nIn enterprise SaaS systems like our **Enterprise HRMS & Automated Payroll** platform (https://hr.solidrix.com/), multi-tenancy ensures that biometric check-in data, payroll tax calculations, and employee salary records remain 100% isolated per client organization.\n\n### 4. Key Performance Recommendations\n\n1. Always add composite indexes on (tenant_id, created_at) for high-frequency queries.\n2. Use Redis caching tagged with tenant_{id} to prevent cross-tenant cache contamination.\n3. Automate database migrations across all tenant databases using background queue workers during maintenance windows.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 1,
            ],
            [
                'title' => "Building High-Throughput Microservices with Node.js & Docker",
                'category' => "Microservices",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "How to design event-driven Node.js microservices wrapped in Docker containers for high concurrency and sub-20ms message processing.",
                'content' => "Microservices architecture breaks down monolithic applications into lightweight, independently deployable services that communicate via high-speed APIs or asynchronous message queues.\n\n### 1. Non-Blocking I/O & Event Loop Optimization\n\nNode.js is inherently single-threaded and non-blocking, making it ideal for I/O-intensive workloads such as API gateways, chat systems, and real-time webhook ingestion. To maximize throughput:\n\n- Avoid blocking the main event loop with CPU-heavy synchronous operations (use Worker Threads or delegate to background job queues).\n- Implement connection pooling for database drivers and Redis clients.\n- Use fast serialization formats (Protocol Buffers or optimized JSON) for inter-service RPC calls.\n\n### 2. Containerizing Node.js Services with Docker\n\nA production-ready Dockerfile for Node.js should use multi-stage builds to minimize container size and security vulnerability surfaces:\n\n```dockerfile\n# Stage 1: Build stage\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\n\n# Stage 2: Production runtime image\nFROM node:20-alpine AS runner\nWORKDIR /app\nUSER node\nCOPY --from=builder /app/node_modules ./node_modules\nCOPY . .\nEXPOSE 3000\nCMD [\"node\", \"server.js\"]\n```\n\n### 3. Service Discovery and Load Balancing\n\nIn containerized production clusters (Kubernetes / Docker Swarm), services discover each other via internal DNS names. Nginx or Traefik acts as an edge reverse proxy routing incoming client traffic to healthy container instances automatically.\n\n### 4. Monitoring & Health Checks\n\nImplement /healthz endpoints in every microservice to report DB connection status, memory utilization, and queue lag. This allows orchestrators to restart failing containers before users experience service degradation.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 2,
            ],
            [
                'title' => "Optimizing Database Queries & Indexing for 10M+ Record Tables",
                'category' => "Database Tuning",
                'image' => "assets/img/projects/hrms.png",
                'summary' => "Proven techniques for reducing MySQL and PostgreSQL query execution time from 4.2 seconds down to 12ms across tables with millions of rows.",
                'content' => "When scaling relational databases past millions of records, standard SELECT queries without proper indexing can lock tables and cause severe server CPU spikes.\n\n### 1. Understanding EXPLAIN & Query Execution Plans\n\nBefore attempting to optimize a slow query, run EXPLAIN ANALYZE in MySQL 8 or PostgreSQL to inspect the execution plan:\n\n- **Type ALL (Full Table Scan):** Indicates the database is checking every single row sequentially. This must be eliminated for high-volume tables.\n- **Type ref or range:** Indicates the query is leveraging an index efficiently.\n\n### 2. Composite Index Ordering Rule (Leftmost Prefix)\n\nWhen creating multi-column composite indexes, column order is paramount. Place the columns used in equality checks first, followed by range checks (>, <, BETWEEN), and finally columns used in ORDER BY:\n\n```sql\n-- Optimal index for: WHERE tenant_id = 5 AND status = 'active' ORDER BY created_at DESC\nCREATE INDEX idx_tenant_status_created ON orders (tenant_id, status, created_at DESC);\n```\n\n### 3. Covering Indexes\n\nA covering index includes all requested SELECT columns within the index B-Tree itself, eliminating the need for the database engine to perform secondary primary key lookups in table storage (Bookmark Lookup).\n\n### 4. Partitioning & Archiving Strategy\n\nFor massive historical tables (e.g. audit logs, biometric check-ins), implement range partitioning by date (YEAR(created_at), MONTH(created_at)). This allows query pruning to scan only the active partition while archiving older partitions to cold storage.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 3,
            ],
            [
                'title' => "Automating Multi-SMTP Email Failover Routing with Real-Time Webhooks",
                'category' => "Infrastructure",
                'image' => "assets/img/projects/solidrix-send.png",
                'summary' => "How Solidrix Send handles high-volume transactional email delivery with dynamic provider failover, bounce parsing, and webhook callbacks.",
                'content' => "Transactional email deliverability (password resets, OTPs, invoices) directly impacts business operations. Relying on a single SMTP gateway creates a single point of failure if the provider experiences downtime or IP throttling.\n\n### 1. Multi-SMTP Router Architecture\n\nIn **Solidrix Send** (https://send.solidrix.com/), we built an intelligent routing engine that distributes email dispatches across multiple tier-1 SMTP providers (Amazon SES, SendGrid, Postmark, Mailgun):\n\n1. **Provider Health Scoring:** Monitors live delivery success rates, bounce rates, and latency for each configured SMTP channel.\n2. **Automatic Dynamic Failover:** If Provider A returns a 5xx error or connection timeout, the email is instantly re-routed through Provider B without dropping the message.\n3. **Queue Processing with Redis:** Incoming HTTP API dispatch requests are acknowledged immediately with a UUID tracking token and queued in Redis for async delivery.\n\n### 2. Webhook Ingestion & Real-Time Event Tracking\n\nDelivery status notifications (Delivered, Bounced, Opened, Spam Complaint) are parsed via incoming webhooks from each provider:\n\n- Normalized event payload structure across different provider formats.\n- Real-time notification dispatched back to client webhooks using exponential backoff retry algorithms.\n- Automatic suppression list management to prevent emailing addresses that generated hard bounces.\n\n### 3. Results Achieved\n\n- **99.99% Inbox Deliverability SLA**\n- **Average Email Dispatch Latency < 450ms**\n- **Zero Single Point of Failure for Critical SaaS Transactional Emails**",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 4,
            ],
            [
                'title' => "Designing Automated Payroll Engines for Enterprise HRMS",
                'category' => "Enterprise SaaS",
                'image' => "assets/img/projects/hrms.png",
                'summary' => "Architecting precision payroll calculation systems handling attendance biometric logs, statutory tax deductions, and automated pay slips.",
                'content' => "Enterprise HRMS systems require absolute mathematical accuracy when processing monthly payroll for thousands of employees across diverse organizational policies.\n\n### 1. Core Payroll Pipeline Components\n\nA production payroll engine consists of five sequential processing pipelines:\n\n1. **Biometric & Shift Log Ingestion:** Parsing raw attendance logs, calculating total worked hours, overtime, late mark penalties, and half-day deductions.\n2. **Leave & Holiday Matrix:** Merging paid leaves, casual leaves, sick leaves, and unexcused Loss of Pay (LOP) days.\n3. **Gross Earning Calculation:** Computing basic salary, House Rent Allowance (HRA), special allowances, performance bonuses, and variable pay.\n4. **Statutory Tax & Deduction Module:** Computing Provident Fund (PF), Employee State Insurance (ESI), Professional Tax (PT), and Tax Deducted at Source (TDS).\n5. **Payslip & Bank Format Generation:** Generating signed PDF payslips and structured bank transfer files (NEFT/RTGS batch CSVs).\n\n### 2. Precision & Floating Point Safety\n\nNever use standard floating-point data types (float / double) for monetary calculations due to binary rounding errors. Always store currency as integer cents/paise or use fixed-point decimal types (DECIMAL(12, 2) in SQL, bcmul() / bcadd() in PHP).\n\n### 3. Audit Trails & Historical Revisions\n\nPayroll calculations must be immutable once finalized. Every payroll run locks the salary structure version, tax slab rates, and employee attendance snapshot used during execution to guarantee historical audit compliance.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 5,
            ],
            [
                'title' => "School ERP System Architecture: Handling High-Concurrency Parent Portals",
                'category' => "EdTech Systems",
                'image' => "assets/img/projects/sklops.png",
                'summary' => "Engineering the SKLOPS school management platform to handle simultaneous report card generation and online fee collection traffic spikes.",
                'content' => "Educational ERP systems experience unique traffic patterns: long periods of steady administrative usage interrupted by sudden, massive concurrency spikes when report cards are published or fee submission deadlines arrive.\n\n### 1. Scaling SKLOPS (https://sklops.com/)\n\nDuring peak exam result releases, thousands of parents log into the mobile app and portal simultaneously. Here is how we engineered **SKLOPS** for seamless responsiveness:\n\n- **Asynchronous PDF Generation:** Generating heavy PDF report cards with charts on-the-fly blocks web worker threads. We pre-generate report card PDFs using background queue workers and store them on Cloud Object Storage (S3 / DigitalOcean Spaces).\n- **Payment Gateway Idempotency:** Online fee submissions require strict idempotency keys to prevent double-charging parents during network drops.\n- **Database Read Replicas:** Admin reporting queries run against MySQL read replicas, keeping the primary master database 100% available for parent fee transactions.\n\n### 2. Real-Time Parent Notifications\n\nParents receive instant push notifications for attendance alerts, homework assignments, and fee receipts via Firebase Cloud Messaging (FCM) integrated directly into the backend workflow.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 6,
            ],
            [
                'title' => "Retail POS Billing Architecture: Real-Time Offline Sync & Thermal Printing",
                'category' => "Retail Tech",
                'image' => "assets/img/projects/vedant-billing.png",
                'summary' => "How Vedant Billing POS provides seamless offline barcode scanning, thermal receipt printing, and background multi-store inventory synchronization.",
                'content' => "In retail supermarket and store billing environments, checkout speed is critical. A billing counter cannot stop operating if internet connectivity drops temporarily.\n\n### 1. Offline-First POS Architecture in Vedant Billing (https://vedantbilling.com/)\n\nWe designed **Vedant Billing POS** with an offline-first client architecture:\n\n- **Local Storage Engine:** Product catalogs, price lists, barcode mappings, and GST tax slabs are cached in client IndexedDB.\n- **Instant Barcode Scanning:** Scanning a barcode fetches the product item instantly from local memory under 5ms.\n- **Direct ESC/POS Thermal Printing:** Communicates directly with USB/Ethernet thermal receipt printers using raw ESC/POS byte commands for sub-second printing.\n- **Background Multi-Store Synchronization:** When network connectivity is restored, pending offline transactions are synced to the central inventory server with conflict resolution algorithms.\n\n### 2. Multi-Store Stock Reconciliation\n\nStore inventories are synchronized in real-time across multiple branch locations, alerting management when stock levels breach re-order thresholds.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 7,
            ],
            [
                'title' => "Mastering Redis Caching Strategies for Sub-50ms API Latency",
                'category' => "Performance",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Effective cache invalidation patterns, Redis data structures (Hashes, Sorted Sets), and pipeline caching for high-speed API responses.",
                'content' => "Redis is an in-memory data structure store used as a database, cache, and message broker. When utilized correctly, Redis can reduce API response latency from 350ms down to sub-15ms.\n\n### 1. Cache Patterns: Cache-Aside vs Write-Through\n\n- **Cache-Aside (Lazy Loading):** The application checks Redis first. If a cache miss occurs, it queries SQL, writes the result to Redis with a TTL, and returns the response.\n- **Write-Through:** Data is updated in SQL and Redis simultaneously, guaranteeing instant consistency for fast-changing data.\n\n### 2. Leveraging Advanced Redis Data Structures\n\nInstead of storing stringified JSON blobs for everything:\n- Use **Redis Hashes (HSET, HGETALL)** for user session objects to fetch individual fields without deserializing full JSON strings.\n- Use **Redis Sorted Sets (ZADD, ZRANGE)** for real-time leaderboards, ranking systems, and rate-limiting sliding windows.\n- Use **Redis Pipelines** to execute batch GET commands in a single network round-trip.\n\n### 3. Preventing Cache Stampede & Cache Penetration\n\nImplement mutex locking (Redis Redlock) when rebuilding expired high-traffic cache keys so only one worker thread queries the database while other requests wait for the cache to refresh.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 8,
            ],
            [
                'title' => "Zero-Downtime Database Migrations in High-Traffic Production Apps",
                'category' => "DevOps & DB",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "How to perform non-blocking column additions, table rewrites, and index creations without locking tables or dropping active API requests.",
                'content' => "Altering database schema on live production tables containing millions of rows can lock tables, cause HTTP 500 errors, and bring down web applications.\n\n### 1. The Expand and Contract Pattern\n\nTo achieve zero downtime during breaking database schema changes, deploy changes in multi-phase releases:\n\n1. **Expand (Add Phase):** Add the new column/table as nullable without dropping the old column.\n2. **Dual-Writing:** Update backend code to write to both old and new columns simultaneously.\n3. **Backfill Data:** Run background migration scripts in small chunks (e.g. 1,000 rows per batch) to populate old data into the new structure.\n4. **Switch Reads:** Update application code to read exclusively from the new column.\n5. **Contract (Cleanup Phase):** Drop old columns/tables in a subsequent deployment.\n\n### 2. Non-Blocking Index Creation\n\nIn PostgreSQL, always create indexes using CREATE INDEX CONCURRENTLY to avoid taking write locks on the table. In MySQL 8, use ALGORITHM=INPLACE, LOCK=NONE for online DDL operations.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 9,
            ],
            [
                'title' => "Building Secure RESTful API Authentication with Sanctum & OAuth2",
                'category' => "Security",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Token management, token refresh mechanisms, rate limiting, and RBAC permissions for public and mobile client APIs.",
                'content' => "Securing API endpoints against unauthorized access, replay attacks, and credential stuffing requires robust token management and authorization middleware.\n\n### 1. Stateful vs Stateless API Authentication\n\n- **Stateful Cookie Sessions (Laravel Sanctum SPA):** Uses HTTP-only, secure, SameSite cookies for single-page web applications. Prevents XSS script token theft.\n- **Stateless Bearer Tokens (Mobile & Third-Party APIs):** Uses hashed Personal Access Tokens (PATs) passed in the Authorization: Bearer <token> header.\n\n### 2. Role-Based Access Control (RBAC) & Scopes\n\nEnforce granular token permissions (abilities / scopes) so that API keys issued to third-party integrations only possess the precise privileges required (e.g. orders:create without users:delete).\n\n### 3. Rate Limiting & Throttling\n\nProtect endpoints against brute-force attacks by configuring IP-based and user-based rate limiters (throttle:60,1) using Redis backends.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 10,
            ],
            [
                'title' => "Linux VPS Hardening & Automated Nginx Reverse Proxy Setup",
                'category' => "Cloud & DevOps",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Step-by-step guide to securing production Linux servers, configuring UFW firewalls, fail2ban, SSH key authentication, and Nginx reverse proxies.",
                'content' => "Deploying web applications directly onto unhardened cloud servers exposes them to automated botnet scanners, SSH brute-force attacks, and DDoS attempts.\n\n### 1. Essential Linux Hardening Checklist\n\n1. **Disable Root SSH Login & Password Auth:** Require SSH key pairs (Ed25519) and enforce custom SSH ports.\n2. **Configure UFW Firewall:** Close all inbound ports except 22 (SSH), 80 (HTTP), and 443 (HTTPS).\n3. **Install Fail2Ban:** Automatically block IP addresses displaying malicious SSH connection behavior.\n4. **Automatic Security Patches:** Enable unattended-upgrades for OS kernel and security updates.\n\n### 2. Production Nginx Reverse Proxy Configuration\n\nNginx acts as the front-line shield for application servers (PHP-FPM / Node.js). Key configuration directives:\n\n```nginx\nserver {\n    listen 443 ssl http2;\n    server_name example.com;\n\n    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;\n    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;\n\n    # Security Headers\n    add_header X-Frame-Options \"SAMEORIGIN\";\n    add_header X-XSS-Protection \"1; mode=block\";\n    add_header X-Content-Type-Options \"nosniff\";\n\n    location / {\n        proxy_pass http://127.0.0.1:3000;\n        proxy_set_header Host \$host;\n        proxy_set_header X-Real-IP \$remote_addr;\n        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n    }\n}\n```",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 11,
            ],
            [
                'title' => "Docker Containerization Best Practices for Production Node & PHP Services",
                'category' => "Docker & Cloud",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Multi-stage Docker builds, image size optimization down to <100MB, non-root user execution, and container health check monitoring.",
                'content' => "Containerizing application workloads ensures 100% environment parity between local development and cloud production.\n\n### 1. Multi-Stage Builds for Minimal Image Size\n\nBy separating build dependencies (compilers, npm devDependencies) from runtime execution layers, production Docker images drop from 1.2GB down to under 90MB.\n\n### 2. Running as Non-Root User\n\nNever run production Docker containers as root. Specify unprivileged system users (USER node or USER www-data) to prevent container breakout vulnerabilities.\n\n### 3. Container Resource Limits & Logging\n\nConfigure CPU and RAM limits (deploy.resources.limits) in Docker Compose to prevent any single buggy process from starving adjacent container services.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 12,
            ],
            [
                'title' => "Managing CI/CD Deployment Pipelines for Large Enterprise Teams",
                'category' => "DevOps",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Automating static analysis, automated unit testing, staging deployments, and zero-downtime production deployment scripts.",
                'content' => "Continuous Integration and Continuous Deployment (CI/CD) pipelines allow engineering teams to ship code safely multiple times a day.\n\n### 1. Pipeline Stages\n\n- **Lint & Static Analysis:** Runs PHPStan / ESLint to catch syntax and type errors automatically.\n- **Automated Test Suite:** Executes unit and integration tests (php artisan test / vitest).\n- **Build Artifact Generation:** Compiles frontend assets (vite build) and caches Docker layers.\n- **Zero-Downtime Deployment:** Deploys new code release directories and updates symlinks automatically (git pull -> composer install -> php artisan migrate -> php artisan config:cache).",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 13,
            ],
            [
                'title' => "Real-Time WebSockets Communication in Modern Web Applications",
                'category' => "Web Architecture",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Implementing bi-directional real-time push notifications, live dashboard metrics, and chat features using Soketi, Pusher, and Laravel Echo.",
                'content' => "Real-time user experiences require bi-directional WebSockets persistent TCP connections instead of legacy polling.\n\n### 1. Self-Hosted Soketi vs Cloud Pusher\n\nSoketi is an open-source, ultra-fast WebSockets server written in Node.js that implements the Pusher protocol natively, handling 100,000+ concurrent connections at a fraction of cloud cost.\n\n### 2. Event Broadcasting Workflow\n\n1. Application triggers a event implementing ShouldBroadcast.\n2. Laravel dispatches event payload to Redis queue.\n3. Soketi worker consumes Redis payload and broadcasts to authenticated channel listeners via WebSockets.\n4. Client browser receives instant event update via Laravel Echo.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 14,
            ],
            [
                'title' => "Designing Event-Driven Microservices with RabbitMQ & Kafka",
                'category' => "Distributed Systems",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Asynchronous message queues, dead-letter exchanges, event sourcing, and idempotent message processing in distributed environments.",
                'content' => "Event-driven architecture decouples producers from consumers using message brokers, ensuring high fault tolerance during service spikes.\n\n### 1. Message Queue Guarantees\n\n- **At-Least-Once Delivery:** Consumers must be designed to be idempotent (processing the same message ID multiple times produces identical results).\n- **Dead Letter Exchanges (DLX):** Unprocessable messages (malformed JSON or database errors) are automatically moved to a DLX queue for developer inspection.\n\n### 2. Kafka vs RabbitMQ Use Cases\n\n- **RabbitMQ:** Ideal for complex routing rules, priority queues, and task worker queues.\n- **Apache Kafka:** Ideal for high-throughput streaming log telemetry and event replay logs.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 15,
            ],
            [
                'title' => "Statutory Tax & Salary Calculation Algorithms in HR Systems",
                'category' => "Financial Tech",
                'image' => "assets/img/projects/hrms.png",
                'summary' => "Mathematical models for computing Provident Fund (PF), Employee State Insurance (ESI), Professional Tax, and Income Tax TDS deductions.",
                'content' => "Indian statutory payroll compliance requires strict adherence to government slab rates and statutory ceilings.\n\n### 1. Statutory Deduction Formulas\n\n- **Provident Fund (PF):** 12% of (Basic + DA), capped at Rs. 1,800/month for statutory wage ceiling of Rs. 15,000.\n- **ESI Deduction:** 0.75% Employee contribution and 3.25% Employer contribution for gross wages up to Rs. 21,000/month.\n- **Professional Tax (PT):** State-specific slab rates (e.g. Maharashtra, Karnataka, UP) deducted based on gross monthly earnings.\n\n### 2. Automated Form 16 & Tax Computation\n\nThe system evaluates Old Regime vs New Tax Regime automatically to select the lowest tax liability for employees during annual IT projection calculations.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 16,
            ],
            [
                'title' => "Building Automated Social Media Marketing (SMM) Provider Integrations",
                'category' => "Automation",
                'image' => "assets/img/projects/solidrix-smm.png",
                'summary' => "How Solidrix SMM automates order routing, balance checks, status polling, and API error recovery across dozens of third-party SMM providers.",
                'content' => "In **Solidrix SMM** (https://smm.solidrix.com), order fulfillment relies on seamless automated API dispatch to upstream provider APIs.\n\n### 1. Automated Provider API Routing Engine\n\n1. **Service Mapping:** Each user service is linked to primary and backup provider service IDs.\n2. **Order Dispatch Queue:** Placed orders are dispatched asynchronously using background worker queues to prevent gateway timeouts.\n3. **Status Synchronization:** Automated cron jobs poll upstream API provider statuses (In progress, Completed, Partial, Canceled) and issue instant wallet refunds if orders drop.\n\n### 2. Balance Monitoring & Safeguards\n\nAutomated balance checks notify system administrators when upstream provider API account balances drop below threshold limits.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 17,
            ],
            [
                'title' => "PostgreSQL vs MySQL: Architectural Selection for Enterprise SaaS",
                'category' => "Database Architecture",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Comparing JSON index capabilities, concurrency models (MVCC), connection pooling, and replication mechanisms between MySQL and Postgres.",
                'content' => "Selecting between MySQL 8 and PostgreSQL 16 is one of the most critical technology decisions when bootstrapping SaaS infrastructure.\n\n### 1. Architectural Comparison\n\n- **JSON Processing:** PostgreSQL JSONB indexes binary JSON efficiently using GIN indexes. MySQL 8 has improved JSON functions but handles multi-valued indexing differently.\n- **Concurrency Control:** PostgreSQL handles heavy concurrent write workloads with minimal lock contention using advanced MVCC.\n- **Connection Handling:** MySQL uses a lightweight thread-per-connection model. Postgres uses process-per-connection, requiring PgBouncer connection pooling for thousands of clients.\n\n### 2. Summary Recommendation\n\nUse MySQL for high-speed read/write web applications with straightforward schemas. Use PostgreSQL for complex analytical queries, geospatial data (PostGIS), or heavy JSONB document querying.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 18,
            ],
            [
                'title' => "Preventing SQL Injection, XSS, and CSRF in Production Codebases",
                'category' => "Cyber Security",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Essential security patterns: PDO parameterized queries, HTML entity escaping, Content Security Policies (CSP), and SameSite cookie policies.",
                'content' => "Application security must be designed into every line of code rather than patched after a security breach.\n\n### 1. SQL Injection Prevention\n\nNever concatenate user input directly into SQL strings. Always use PDO prepared statements with bound parameters:\n\n```php\n// WRONG (Vulnerable to SQLi):\nDB::select(\"SELECT * FROM users WHERE email = '\" . \$input . \"'\");\n\n// RIGHT (Safe Parameterized Query):\nDB::select(\"SELECT * FROM users WHERE email = ?\", [\$input]);\n```\n\n### 2. Cross-Site Scripting (XSS) Prevention\n\nAlways escape HTML output when rendering user-submitted text (e() or {{ }} in Blade). Implement strict Content Security Policy (CSP) headers to block unauthorized script execution.\n\n### 3. CSRF Protection\n\nEnforce anti-CSRF token verification (@csrf) on all state-changing HTTP POST, PUT, and DELETE requests.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 19,
            ],
            [
                'title' => "Designing Scalable Subdomain & Custom Domain Routing in Laravel",
                'category' => "SaaS Engineering",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Allowing SaaS tenants to bind custom domain names with automated Let\u2019s Encrypt SSL certificate issuance via CNAME DNS validation.",
                'content' => "Allowing enterprise customers to use their own custom domain name (e.g. hrms.clientcompany.com) elevates your SaaS product.\n\n### 1. Custom Domain DNS Validation\n\nTenants create a CNAME DNS record pointing hrms.clientcompany.com to app.yourdomain.com.\n\n### 2. Automated SSL Certificate Provisioning\n\nUsing Caddy Server or Nginx with Let's Encrypt / ACME HTTP-01 challenge automation, SSL certificates are issued dynamically when custom domain requests arrive.\n\n### 3. Route Matching Middleware\n\nLaravel checks the incoming Host header against registered custom domain records in the database, mapping the request to the target tenant container seamlessly.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 20,
            ],
            [
                'title' => "Effective Monitoring & Log Aggregation for Distributed Systems",
                'category' => "DevOps",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Centralizing server logs with Grafana Loki, setting up error tracking alerts via Sentry, and monitoring system metrics with Prometheus.",
                'content' => "Without centralized logging and real-time error tracking, diagnosing production issues across multiple microservices is nearly impossible.\n\n### 1. The Observability Triad\n\n1. **Metrics (Prometheus & Grafana):** CPU, RAM, disk I/O, network throughput, and API response time percentiles (p95, p99).\n2. **Logs (Grafana Loki & Promtail):** Centralized log aggregation allowing developers to search logs across all server instances simultaneously.\n3. **Traces (Sentry / OpenTelemetry):** Distributed tracing tracking an HTTP request's execution path across multiple microservice boundaries.\n\n### 2. Alert Escalation\n\nSet up automated Discord/Slack and PagerDuty notifications for unhandled 5xx server exceptions or CPU usage exceeding 90% for over 5 minutes.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 21,
            ],
            [
                'title' => "From Technical Lead to Technical Founder: Lessons in Software Architecture",
                'category' => "Leadership",
                'image' => "assets/img/rohit.jpeg",
                'summary' => "Insights on balancing fast product iteration with long-term code maintainability, technical debt management, and team leadership.",
                'content' => "Transitioning from engineering lead to technical founder requires balancing code craftsmanship with business velocity.\n\n### 1. Managing Technical Debt\n\nNot all technical debt is bad. Early-stage products need speed to validate market demand. However, architectural decisions around data models and authentication must be solid from day one, as refactoring them later is exponentially more expensive.\n\n### 2. Pragmatic Technology Selection\n\nAvoid adopting shiny new frameworks for mission-critical core systems without proven ecosystem stability. Proven stacks like Laravel, Node.js, and MySQL allow small teams to ship production software reliably.\n\n### 3. Team Empowerment & Code Reviews\n\nFocus on establishing clear architectural guidelines, automated CI/CD checks, and constructive code reviews that empower engineers to own product modules independently.",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 22,
            ],
            [
                'title' => "High-Availability Database Clustering & Automated Failover",
                'category' => "Database Architecture",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Setting up MySQL Orchestrator & PostgreSQL Patroni for zero-data-loss database clustering and instant node failover.",
                'content' => "Database high availability requires synchronous replication, health checks, and automated VIP switching...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 23,
            ],
            [
                'title' => "Architecting Enterprise Single Sign-On (SSO) with SAML 2.0 & OAuth2",
                'category' => "Security",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Implementing corporate SSO login integrations (Okta, Azure AD, Google Workspace) in multi-tenant SaaS platforms.",
                'content' => "Enterprise B2B clients demand SAML 2.0 and OpenID Connect (OIDC) Single Sign-On to enforce corporate security policies...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 24,
            ],
            [
                'title' => "Building Real-Time Audit Log Telemetry for Regulatory Compliance",
                'category' => "Enterprise SaaS",
                'image' => "assets/img/projects/hrms.png",
                'summary' => "Immutable audit logging patterns using Redis stream buffering and elastic search archiving for SOC2 & ISO 27001 compliance.",
                'content' => "Every user action in enterprise systems must be logged with actor IP, timestamp, entity change diffs, and cryptographic checksums...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 25,
            ],
            [
                'title' => "Optimizing Node.js Garbage Collection for Memory-Intensive Workloads",
                'category' => "Performance",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Tuning V8 engine heap size (--max-old-space-size), profiling heap snapshots, and eliminating closure memory leaks.",
                'content' => "Node.js applications processing large payloads can encounter out-of-memory crashes if V8 GC pauses become excessive...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 26,
            ],
            [
                'title' => "Designing High-Performance Financial Ledger Systems",
                'category' => "Financial Tech",
                'image' => "assets/img/projects/vedant-billing.png",
                'summary' => "Double-entry accounting database schema, strict transaction isolation levels, and automated ledger balancing scripts.",
                'content' => "Financial platforms require strict double-entry ledger architecture where debits equal credits in every transaction context...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 27,
            ],
            [
                'title' => "Building Custom Background Job Queue Drivers in PHP & Node.js",
                'category' => "Backend Architecture",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Implementing custom Redis-backed worker queues with priority weights, delay scheduling, and graceful shutdown listeners.",
                'content' => "Understanding job queues from first principles enables building resilient background processing systems...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 28,
            ],
            [
                'title' => "Serverless Cloud Functions vs Containerized Microservices: A Real-World Comparison",
                'category' => "Cloud & DevOps",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Cost analysis, cold start latency considerations, and architectural trade-offs between AWS Lambda and Docker Fargate.",
                'content' => "Comparing serverless execution models against long-running containerized clusters for high-volume enterprise APIs...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 29,
            ],
            [
                'title' => "Building Rate Limiters with Token Bucket & Sliding Window Algorithms",
                'category' => "API Design",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Protecting public APIs against denial-of-service using Redis Lua scripts for atomic sliding window rate limiting.",
                'content' => "Rate limiting algorithms protect backend services from abusive traffic spikes and DDoS attacks...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 30,
            ],
            [
                'title' => "GraphQL vs REST: Designing Modern API Architectures for Mobile Apps",
                'category' => "API Design",
                'image' => "assets/img/services/backend-architecture.png",
                'summary' => "Over-fetching prevention, schema stitching, N+1 query solving with DataLoader, and caching strategies.",
                'content' => "Selecting API query layers for complex client applications requires evaluating GraphQL schema benefits against REST simplicity...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 31,
            ],
            [
                'title' => "Building Zero-Trust API Networks with Mutual TLS (mTLS) & Service Mesh",
                'category' => "Cyber Security",
                'image' => "assets/img/services/saas-devops.png",
                'summary' => "Securing inter-service microservice communications using Istio service mesh and dynamic mTLS certificate rotation.",
                'content' => "Zero-trust architecture enforces strict cryptographic authentication for every internal microservice connection...",
                'author' => "Rohit Kumar (Coolhax RK)",
                'sub_days' => 32,
            ],
        ];

        foreach ($blogs as $b) {
            Blog::create([
                'title' => $b['title'],
                'slug' => Str::slug($b['title']),
                'category' => $b['category'],
                'image' => $b['image'],
                'summary' => $b['summary'],
                'content' => $b['content'],
                'author' => $b['author'],
                'is_published' => true,
                'published_at' => Carbon::now()->subDays($b['sub_days']),
            ]);
        }
    }
}
